class ApiConstants {
  static String pubDevPackageUrl(String packageName) => 'https://pub.dev/api/packages/$packageName';

  static String githubRepoUrl(String owner, String repo) =>
      'https://api.github.com/repos/$owner/$repo';

  static String githubRawContentUrl(String owner, String repo, String branch, String path) =>
      'https://raw.githubusercontent.com/$owner/$repo/$branch/$path';

  static String githubContentsUrl(String owner, String repo, String branch, String dirPath) =>
      'https://api.github.com/repos/$owner/$repo/contents/$dirPath?ref=$branch';

  /// URL to the Dartdoc-generated index.json for a specific package version.
  /// The index.json contains the full structural taxonomy of the package's
  /// public API as generated by `dartdoc` at publish time.
  static String pubDevDartdocIndexUrl(String packageName, String version) =>
      'https://pub.dev/documentation/$packageName/$version/index.json';
  static String githubSearchUrl(String query) =>
      'https://api.github.com/search/code?q=${Uri.encodeComponent(query)}';
}
